### ISSUE TITLE
Add support for multiple monitors with taskbar mirrored to both

### ISSUE THREAD

**Issue by Gonaah** [hatelamers/WinPinMenu#4]
I placed the shortcut in the taskbar favorites, when I click it it works but the menu appears on the secondary monitor
![2024-11-13_17-10](https://github.com/user-attachments/assets/9c214a18-845d-4cc1-b73e-f265f932b8f7)

**Comment by hatelamers** [comment]
Thanks for reporting.

Multiple monitors with the same taskbar icons on both aren't yet supported but it is certainly worth working on it.

With your consent I am modding this issue into a feature request.

**Comment by Gonaah** [comment]
thank u <3

**Comment by hatelamers** [comment]
I've drafted a pre-release https://github.com/hatelamers/WinPinMenu/releases/tag/v0.1.1-pre01 with support for multi-monitor and dark mode. Care to test it out?

**Comment by Gonaah** [comment]
Very nice! I'm going to start using it now, the only problem is that it takes a little while for the menu to appear when you click on it, but other than that it's perfect! Thank you!
